apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: polaris
spec:
  replicas: 5

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: polaris
spec:
  replicas: 3
